# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: localhost
  pool: 5
  database: daily_recommend
  username: active
  password: '@ctive123'


production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: 
  #  port: 3306
  database: daily_promotion
  pool: 5
  username: 
  password: 

